-- 008_gap_audit (down) — remove the gap-audit review queue.
--
-- migrate: DESTRUCTIVE — drops price_gap_audit, which holds gap classifications including
-- operator decisions (halt_accepted rows record human judgement that is NOT recomputable; the
-- machine-derived dispositions can be regenerated by re-running load_delistings.py audit).

DROP TABLE IF EXISTS price_gap_audit;
